/*
LogCom API

Testing NotificationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package logcomapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_logcomapi_NotificationApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test NotificationApiService CreateNotificationV1", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.NotificationApi.CreateNotificationV1(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test NotificationApiService GetNotificationMessagesV1", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.NotificationApi.GetNotificationMessagesV1(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test NotificationApiService PeekNotificationMessagesV1", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.NotificationApi.PeekNotificationMessagesV1(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test NotificationApiService UpdateNotificationMessageV1", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var id uuid.UUID

        resp, httpRes, err := apiClient.NotificationApi.UpdateNotificationMessageV1(context.Background(), id).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
