/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.2.6
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

// The notification event category
type CreateNotificationRequestDtoEventCategory struct {
}
