/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.0.0
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

type ModelsLogLevel int32

// List of models.LogLevel
const (
	_0 ModelsLogLevel = 0
	_1 ModelsLogLevel = 1
	_2 ModelsLogLevel = 2
	_3 ModelsLogLevel = 3
	_4 ModelsLogLevel = 4
	_5 ModelsLogLevel = 5
	MINUS_1 ModelsLogLevel = -1
)
