/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.2.5
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

// The status of the message
type NotificationMessageDtoStatus struct {
}
