/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.2.6
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

import (
	"github.com/google/uuid"
	"time"
)

type ConsoleLogDto struct {
	// The log timestamp
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// The user's ID who created
	CreatedById *uuid.UUID `json:"createdById,omitempty"`
	// The user's name who created
	CreatedByName string `json:"createdByName,omitempty"`
	// The ID
	Id *uuid.UUID `json:"id,omitempty"`
	Level *ConsoleLogDtoLevel `json:"level,omitempty"`
	// The log message
	Message string `json:"message,omitempty"`
	// The request ID making dependent logs trackable
	RequestId *uuid.UUID `json:"requestId,omitempty"`
	// The service which sent the log
	Service string `json:"service,omitempty"`
}
