/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.2.7
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

// The log level (Trace=-1, Debug=0, Info=1, Warning=2, Error=3, Fatal=4, Panic=5)
type ConsoleLogDtoLevel struct {
}
