/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.2.7
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

type ModelsNotificationStatus string

// List of models.NotificationStatus
const (
	ERROR_ ModelsNotificationStatus = "ERROR"
	NEW ModelsNotificationStatus = "NEW"
	SEEN ModelsNotificationStatus = "SEEN"
	SENT ModelsNotificationStatus = "SENT"
)
