/*
 * LogCom API
 *
 * LogCom Swagger documentation
 *
 * API version: 1.0.0
 * Contact: laborit@blutspende.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package logcomapi

type ModelsSortDirection string

// List of models.SortDirection
const (
	ASC ModelsSortDirection = "asc"
	DESC ModelsSortDirection = "desc"
	EMPTY ModelsSortDirection = ""
)
